name: Bug Report
description: File a bug report
body:
- type: markdown
  attributes:
    value: |
      ## Read First
      * Do not request help with using get_iplayer. User support will not be provided.
      * Do not request new features for get_iplayer. Feature requests will not be accepted.
      * All bug reports will automatically be closed and locked upon receipt.
      * If your report identifies a reproducible bug in get_iplayer, it will be re-opened until a fix is released.
      * You will receive no communication from the developers, so provide all the information required.  
- type: checkboxes
  attributes:
    label: Do not file a bug report if you are using get_iplayer outside the UK. If you do, your report will be ignored.
    options:
    - label: I am not using get_iplayer outside the UK
      required: true
- type: checkboxes
  attributes:
    label: Do not file a bug report if you are using get_iplayer with a VPN or proxy from any location, including the UK. If you do, your report will be ignored.
    options:
    - label: I am not using get_iplayer with a VPN or proxy from any location, including the UK
      required: true
- type: checkboxes
  attributes:
    label: Search the repository (search field at top left) to see if a report already exists for the bug in the issue tracker. Do not create a duplicate report. Duplicate reports will be ignored.
    description: See - **[Issue Tracker](https://github.com/get-iplayer/get_iplayer/issues)**
    options:
    - label: I have searched the repository and found no existing reports of the bug in the issue tracker
      required: true
- type: checkboxes
  attributes:
    label: Review recent open and closed entries in the issue tracker to see if a report already exists for the bug. Do not create a duplicate report. Duplicate reports will be ignored.
    description: See - [Open Issues](https://github.com/get-iplayer/get_iplayer/issues?q=is%3Aopen+is%3Aissue), [Closed Issues](https://github.com/get-iplayer/get_iplayer/issues?q=is%3Aclosed+is%3Aissue)
    options:
    - label: I have reviewed recent open and closed entries in the issue tracker and found no existing reports of the bug
      required: true
- type: checkboxes
  attributes:
    label: Ensure that you are using get_iplayer 3.31 or higher. If not, your report will be ignored.
    description: Check version with **`get_iplayer -V` or see the bottom of the Web PVR search page**
    options:
    - label: I am using get_iplayer 3.31 or higher
      required: true
- type: input
  attributes:
    label: Identify the operating system and version where get_iplayer demonstrates the bug
    description: Examples - Ubuntu 20.04, Fedora 34, Arch, OpenBSD 6.8, macOS 10.14, macOS Monterey (M1), Windows 10
  validations:
    required: true
- type: textarea
  attributes:
    label: Provide a clear and concise description of the bug. Do not paste get_iplayer output or screenshots into the field below. If you do, your report will be ignored.
  validations:
    required: true
- type: input
  attributes:
    label: Provide the PID or URL of the programme you are attempting to download, if applicable. Provide the PID or URL for only one programme.    
  validations:
    required: false
- type: textarea
  attributes:
    label: Provide the complete get_iplayer command line that demonstrates the bug. Do not truncate or excerpt the command. If you do, your report will be ignored. If you are using the Web PVR, list the steps necessary to reproduce the bug, in as much detail as possible.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Create a verbose log file for the bug, e.g., "log.txt" using the `--verbose` option:
      ```bash
      get_iplayer [your options here] --verbose > log.txt 2>&1
      ```
      ### Do not truncate or excerpt the log file. If you do, your report will be ignored. If you are using the Web PVR, copy output from both your web browser and the Web PVR console window and paste it into a plain text file. Do not omit the console window output showing the get_iplayer command(s) invoked by the Web PVR. If you do, your report will be ignored. To minimise the amount of output in the console window, quit and restart the Web PVR, then immediately execute the command that demonstrates the bug.
      ### Do not submit screenshots instead of a log file. If you do, your report will be ignored.
- type: textarea
  attributes:
    label: Drag the log file into the field below to create an attachment. The log file must be added as an attachment. Do not paste its contents into the field below. If you do, your report will be ignored. You may enter a URL linking to your log file on a pastebin site. If the bug prevents get_iplayer from running, enter "N/A" in the field below. If you enter any other text in the field below, your report will be ignored.
  validations:
    required: true
- type: input
  attributes:
    label: If you are using the Web PVR, provide your web browser name and version. This information typically can be found from the application menu via Chrome/Firefox/Safari->About... (macOS) or Help->About... (Linux/Windows)
    description: Examples - Chrome 83.0.4103, Edge 83.0.478.56, Firefox 78.0.1, Safari 13.1.1
  validations:
    required: false
